# Generated by Django 3.0.9 on 2020-08-27 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='cpueff',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='emailed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='jobid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='memeff',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
