# Generated by Django 3.0.9 on 2020-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0002_auto_20200827_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='efficiency',
            old_name='memeff',
            new_name='mem_eff',
        ),
        migrations.AddField(
            model_name='efficiency',
            name='mem_requested',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='mem_used',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
