# Generated by Django 3.0.9 on 2020-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0003_auto_20200827_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='number_of_cpus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efficiency',
            name='number_of_nodes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
