# Generated by Django 3.0.9 on 2020-08-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0005_remove_efficiency_number_of_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='number_of_nodes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
