# Generated by Django 3.0.9 on 2021-02-04 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0006_efficiency_number_of_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='job_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
