# Generated by Django 3.2.3 on 2021-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0007_efficiency_job_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiency',
            name='jobid',
            field=models.CharField(max_length=100),
        ),
    ]
