# Generated by Django 3.2.3 on 2022-02-28 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0009_efficiency_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='job_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
