# Generated by Django 3.0.9 on 2020-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200519_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.CharField(default='pXXX', max_length=7),
            preserve_default=False,
        ),
    ]
